;;; balanced-theme.el --- A balanced and subtle theme -*- lexical-binding: t -*-
;;; Commentary:
;; 
;;; Code:

(deftheme balanced-light "A light balanced and subtle theme." '(:family 'custom :background-mode 'light))

(require 'color)
(require 'cl-lib)

(defvar balanced/bg "#ffffff")
(defvar balanced/fg-subtle "#acbbc3")
(defvar balanced/fg-neutral "#425259")
(defvar balanced/fg-vibrant "#161616")
(defvar balanced/error "#d73737")
(defvar balanced/warning "#d88421")
(defvar balanced/operator "#374151")
(defvar balanced/selection "#f4f4f5")
(defvar balanced/comment "#819097")
(defvar balanced/string "#00897b")
(defvar balanced/keyword "#b98acc")
(defvar balanced/function "#0d47a1")
(defvar balanced/constant "#7c4dff")

(custom-theme-set-faces 'balanced-light
                        `(default ((t . (:background ,balanced/bg :foreground ,balanced/fg-subtle))))
                        `(cursor ((t . (:background ,balanced/fg-vibrant))))
                        `(region ((t . (:background ,balanced/selection))))
                        `(fringe ((t . (:background ,balanced/bg))))
                        `(mode-line ((t . (:background ,balanced/fg-subtle :foreground ,balanced/fg-neutral))))
                        `(font-lock-bracket-face ((t . (:background-color ,balanced/operator))))
	                    `(font-lock-builtin-face ((t . (:foreground ,balanced/function))))
	                    `(font-lock-comment-delimiter-face ((t . (:foreground ,balanced/string))))
	                    `(font-lock-comment-face ((t . (:foreground ,balanced/comment))))
	                    `(font-lock-constant-face ((t . (:foreground ,balanced/constant))))
	                    `(font-lock-delimiter-face ((t . (:foreground ,balanced/operator))))
	                    `(font-lock-doc-face ((t . (:foreground ,balanced/comment))))
	                    `(font-lock-doc-markup-face ((t . (:foreground ,balanced/string))))
	                    `(font-lock-escape-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-function-call-face ((t . (:foreground ,balanced/fg-vibrant))))
	                    `(font-lock-function-name-face ((t . (:foreground ,balanced/function))))
	                    `(font-lock-keyword-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-misc-punctuation-face ((t . (:foreground ,balanced/operator))))
	                    `(font-lock-negation-char-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-number-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-operator-face ((t . (:foreground ,balanced/operator))))
	                    `(font-lock-preprocessor-face ((t . (:foreground ,balanced/comment))))
	                    `(font-lock-property-name-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-property-use-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-punctuation-face ((t . (:foreground ,balanced/operator))))
	                    `(font-lock-regexp-face ((t . (:foreground ,balanced/string))))
	                    `(font-lock-regexp-grouping-backslash ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-regexp-grouping-construct ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-string-face ((t . (:foreground ,balanced/string))))
	                    `(font-lock-type-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-variable-name-face ((t . (:foreground ,balanced/fg-neutral))))
	                    `(font-lock-variable-use-face  ((t . (:foreground ,balanced/fg-neutral))))
	                    `(font-lock-warning-face ((t . (:foreground ,balanced/warning))))
	                    `(magit-header-line ((t . (:foreground ,balanced/fg-vibrant))))
	                    `(magit-section-heading ((t . (:foreground ,balanced/fg-vibrant :weight bold))))
	                    `(magit-tag ((t . (:foreground ,balanced/fg-vibrant))))
	                    `(magit-head ((t . (:foreground ,balanced/string))))
                        )

(provide-theme 'balanced-light)
;;; balanced-light-theme.el ends here.
