;;; balanced-theme.el --- A balanced and subtle theme -*- lexical-binding: t -*-
;;; Commentary:
;; 
;;; Code:

(deftheme balanced "A balanced and subtle theme." '(:family 'custom :background-mode 'dark))

(require 'color)
(require 'cl-lib)

(defvar balanced/bg "#262730")
(defvar balanced/fg-subtle "#9099a3")
(defvar balanced/fg-neutral "#bfdef2")
(defvar balanced/fg-vibrant "#f4f4f5")
(defvar balanced/error "#f79199")
(defvar balanced/warning "#eb9947")
(defvar balanced/operator "#f791199")
(defvar balanced/selection "#494a51")
(defvar balanced/comment "#85f797")
(defvar balanced/string "#69c997")
(defvar balanced/keyword "#f79199")
(defvar balanced/function "#f7f7a3")
(defvar balanced/constant "#f77aee")

(custom-theme-set-faces 'balanced
                        `(default ((t . (:background ,balanced/bg :foreground ,balanced/fg-subtle))))
                        `(cursor ((t . (:background ,balanced/fg-vibrant))))
                        `(region ((t . (:background ,balanced/selection))))
                        `(fringe ((t . (:background ,balanced/bg))))
                        `(mode-line ((t . (:background ,balanced/fg-subtle :foreground ,balanced/fg-neutral))))
                        `(font-lock-bracket-face ((t . (:background-color ,balanced/operator))))
	                    `(font-lock-builtin-face ((t . (:foreground ,balanced/function))))
	                    `(font-lock-comment-delimiter-face ((t . (:foreground ,balanced/string))))
	                    `(font-lock-comment-face ((t . (:foreground ,balanced/comment))))
	                    `(font-lock-constant-face ((t . (:foreground ,balanced/constant))))
	                    `(font-lock-delimiter-face ((t . (:foreground ,balanced/operator))))
	                    `(font-lock-doc-face ((t . (:foreground ,balanced/comment))))
	                    `(font-lock-doc-markup-face ((t . (:foreground ,balanced/string))))
	                    `(font-lock-escape-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-function-call-face ((t . (:foreground ,balanced/fg-vibrant))))
	                    `(font-lock-function-name-face ((t . (:foreground ,balanced/function))))
	                    `(font-lock-keyword-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-misc-punctuation-face ((t . (:foreground ,balanced/operator))))
	                    `(font-lock-negation-char-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-number-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-operator-face ((t . (:foreground ,balanced/operator))))
	                    `(font-lock-preprocessor-face ((t . (:foreground ,balanced/comment))))
	                    `(font-lock-property-name-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-property-use-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-punctuation-face ((t . (:foreground ,balanced/operator))))
	                    `(font-lock-regexp-face ((t . (:foreground ,balanced/string))))
	                    `(font-lock-regexp-grouping-backslash ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-regexp-grouping-construct ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-string-face ((t . (:foreground ,balanced/string))))
	                    `(font-lock-type-face ((t . (:foreground ,balanced/keyword))))
	                    `(font-lock-variable-name-face ((t . (:foreground ,balanced/fg-neutral))))
	                    `(font-lock-variable-use-face  ((t . (:foreground ,balanced/fg-neutral))))
	                    `(font-lock-warning-face ((t . (:foreground ,balanced/warning))))
                        )

(provide-theme 'balanced)
;;; balanced-theme.el ends here.
